#! /usr/bin/env node

const fs = require('fs');
const fileName='./apiKey.js';
const text='const apiKey = "' + process.env.CROQUET_APIKEY +'";\n' +
           'const appId = "' + process.env.CROQUET_APPID + '";\n' +
           'export default {apiKey, appId};\n' +
           '\n\n///This file was autogenerated with scripts/make_apiKey.js.\n';

fs.writeFile(fileName, text, function(err) {
        if (err) throw err; 
        console.log('apiKey.js created successfully.');
});
